import { Inter } from 'next/font/google'
import { Theme, ThemePanel } from '@radix-ui/themes'
import { Analytics } from '@vercel/analytics/react'

import './globals.css'
import '@radix-ui/themes/styles.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ironhaus',
  description: 'Generated by Ironhaus',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Theme>
        <body className={`${inter.className} bg-gradient-to-r from-black to-gray-900`}>{children}</body>
      </Theme>
      <Analytics />
    </html>
  )
}
